services:
  app:
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    build: .
    container_name: alura-api
    ports:
      # Mapeia a porta 8000 do seu computador (host) para a porta 8000 do container,
      # que é a porta que o Uvicorn está usando (definida no Dockerfile).
      - "8000:8000"
    volumes:
      # Monta o diretório atual ('.') no diretório '/app' do container.
      # Isso garante que o hot-reload do Uvicorn funcione, pois o WORKDIR no seu Dockerfile é /app.
      - .:/app
